### ISSUE TITLE
Rest web service using spring boot and json-ld

### ISSUE THREAD

**Issue by Rakeshjdev** [kbss-cvut/jopa-examples#2]
I am new to json -ld .  dont know how to use  json -ld  with spring boot . in Get ,post,delete and put method. can you please add one example to new learner. i searched much on the  web but did not get any help.

**Comment by ledsoft** [comment]
Hi, take a look at the [json-ld demo](https://github.com/kbss-cvut/jopa-examples/tree/master/jsonld), the set up is pretty straightforward and, hopefully, the readme explains the process.

**Comment by Rakeshjdev** [comment]
I am trying to set up unfortunately getting below error please help me 

05-07-2019 12:25:46.587 [main] ERROR c.c.k.j.j.p.dao.BaseDao - Error when persisting entity.
java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at cz.cvut.kbss.jopa.model.BeanListenerAspect.register(BeanListenerAspect.java:84)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.registerEntityWithPersistenceContext(UnitOfWorkImpl.java:623)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.registerNewObjectInternal(UnitOfWorkImpl.java:752)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.registerNewObject(UnitOfWorkImpl.java:727)
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.persist(EntityManagerImpl.java:88)
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.persist(EntityManagerImpl.java:74)
	at com.github.ledsoft.jopa.spring.transaction.DelegatingEntityManager.persist(DelegatingEntityManager.java:27)
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.BaseDao.persist(BaseDao.java:63)
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.DerivableUriDao.persist(DerivableUriDao.java:15)
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.UserDao.persist(UserDao.java:23)
	at cz.cvut.kbss.jopa.jsonld.service.repository.UserRepositoryService.lambda$0(UserRepositoryService.java:59)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at cz.cvut.kbss.jopa.jsonld.service.repository.UserRepositoryService.initDefaultUser(UserRepositoryService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:309)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1691)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at cz.cvut.kbss.jopa.jsonld.JsonLdDemo.main(JsonLdDemo.java:10)
05-07-2019 12:25:46.588 [main] DEBUG c.g.l.j.s.t.JopaTransactionManager - Initiating transaction rollback
05-07-2019 12:25:46.588 [main] DEBUG c.g.l.j.s.t.JopaTransactionManager - Commencing transaction rollback.
05-07-2019 12:25:46.588 [main] TRACE c.c.k.j.s.AbstractSession - UnitOfWork rollback started.
05-07-2019 12:25:46.589 [main] TRACE c.c.k.o.s.c.StorageConnector - Releasing repository connection.
05-07-2019 12:25:46.590 [main] ERROR o.s.t.s.TransactionTemplate - Application exception overridden by rollback exception
cz.cvut.kbss.jopa.jsonld.persistence.PersistenceException: java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.BaseDao.persist(BaseDao.java:66)
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.DerivableUriDao.persist(DerivableUriDao.java:15)
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.UserDao.persist(UserDao.java:23)
	at cz.cvut.kbss.jopa.jsonld.service.repository.UserRepositoryService.lambda$0(UserRepositoryService.java:59)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at cz.cvut.kbss.jopa.jsonld.service.repository.UserRepositoryService.initDefaultUser(UserRepositoryService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:309)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1691)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at cz.cvut.kbss.jopa.jsonld.JsonLdDemo.main(JsonLdDemo.java:10)
Caused by: java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at cz.cvut.kbss.jopa.model.BeanListenerAspect.register(BeanListenerAspect.java:84)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.registerEntityWithPersistenceContext(UnitOfWorkImpl.java:623)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.registerNewObjectInternal(UnitOfWorkImpl.java:752)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.registerNewObject(UnitOfWorkImpl.java:727)
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.persist(EntityManagerImpl.java:88)
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.persist(EntityManagerImpl.java:74)
	at com.github.ledsoft.jopa.spring.transaction.DelegatingEntityManager.persist(DelegatingEntityManager.java:27)
	at cz.cvut.kbss.jopa.jsonld.persistence.dao.BaseDao.persist(BaseDao.java:63)
	... 58 common frames omitted
05-07-2019 12:25:46.591 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyController' defined in file [C:\Users\VKu56Ra\Downloads\jopa-examples-master\jopa-examples-master\jsonld\target\classes\cz\cvut\kbss\jopa\jsonld\rest\StudyController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyRepositoryService' defined in file [C:\Users\VKu56Ra\Downloads\jopa-examples-master\jopa-examples-master\jsonld\target\classes\cz\cvut\kbss\jopa\jsonld\service\repository\StudyRepositoryService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepositoryService': Invocation of init method failed; nested exception is java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
05-07-2019 12:25:46.592 [main] WARN  o.s.b.f.s.DisposableBeanAdapter - Destroy method 'close' on bean with name 'getEntityManagerFactory' threw an exception: java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
05-07-2019 12:25:46.592 [main] WARN  o.s.c.a.CommonAnnotationBeanPostProcessor - Invocation of destroy method failed on bean with name 'persistenceFactory': java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
05-07-2019 12:25:46.595 [main] INFO  o.a.c.core.StandardService - Stopping service [Tomcat]
05-07-2019 12:25:46.610 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
05-07-2019 12:25:46.611 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyController' defined in file [C:\Users\VKu56Ra\Downloads\jopa-examples-master\jopa-examples-master\jsonld\target\classes\cz\cvut\kbss\jopa\jsonld\rest\StudyController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyRepositoryService' defined in file [C:\Users\VKu56Ra\Downloads\jopa-examples-master\jopa-examples-master\jsonld\target\classes\cz\cvut\kbss\jopa\jsonld\service\repository\StudyRepositoryService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepositoryService': Invocation of init method failed; nested exception is java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at cz.cvut.kbss.jopa.jsonld.JsonLdDemo.main(JsonLdDemo.java:10)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyRepositoryService' defined in file [C:\Users\VKu56Ra\Downloads\jopa-examples-master\jopa-examples-master\jsonld\target\classes\cz\cvut\kbss\jopa\jsonld\service\repository\StudyRepositoryService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepositoryService': Invocation of init method failed; nested exception is java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepositoryService': Invocation of init method failed; nested exception is java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1691)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	... 33 common frames omitted
Caused by: java.lang.ClassCastException: cz.cvut.kbss.jopa.jsonld.model.User cannot be cast to cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable
	at cz.cvut.kbss.jopa.model.BeanListenerAspect.deregister(BeanListenerAspect.java:94)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.deregisterEntityFromPersistenceContext(UnitOfWorkImpl.java:627)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.lambda$detachAllManagedInstances$2(UnitOfWorkImpl.java:236)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.detachAllManagedInstances(UnitOfWorkImpl.java:234)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.clear(UnitOfWorkImpl.java:213)
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.release(UnitOfWorkImpl.java:676)
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.removeCurrentPersistenceContext(EntityManagerImpl.java:557)
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.close(EntityManagerImpl.java:387)
	at com.github.ledsoft.jopa.spring.transaction.JopaTransactionManager.doCleanupAfterCompletion(JopaTransactionManager.java:93)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1007)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:878)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:812)
	at org.springframework.transaction.support.TransactionTemplate.rollbackOnException(TransactionTemplate.java:168)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:144)
	at cz.cvut.kbss.jopa.jsonld.service.repository.UserRepositoryService.initDefaultUser(UserRepositoryService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:309)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 46 common frames omitted
05-07-2019 12:25:46.613 [RepositoryProvider-shutdownHook] DEBUG o.e.r.s.nativerdf.NativeStore - Shutting down NativeStore...
05-07-2019 12:25:46.628 [RepositoryProvider-shutdownHook] DEBUG o.e.r.s.nativerdf.NativeStore - NativeStore shut down
05-07-2019 12:25:46.631 [RepositoryProvider-shutdownHook] DEBUG o.e.r.s.nativerdf.NativeStore - NativeStore shut down

**Comment by ledsoft** [comment]
Make sure to build the project using Maven. It runs the aspectj plugin, which weaves aspects into the entity classes. Sometimes, it happens that the build gets messed up and this exception can occur. In that case, clean the project and rerun the build.
Hope this helps.

**Comment by Rakeshjdev** [comment]
Thanks you  worked for me.
